name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  testbouncycastle:
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: useblacksmith/setup-gradle/setup-gradle@v666

      - name: Run Checks
        run: ./gradlew test -Dokhttp.platform=bouncycastle
