name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

  validation:
    name: "Validation"
    runs-on: blacksmith
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - name: Validate Renovate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: '.github/renovate.json'

  checkjdk11:
    permissions:
      checks: write # for mikepenz/action-junit-report
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check -PandroidBuild=true -PgraalBuild=true -x test -x test

  testopenjdk11:
    permissions:
      checks: write # for mikepenz/action-junit-report
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -Dtest.java.version=11

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          check_name: OpenJDK 11 Test Report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/build/test-results/*/TEST-*.xml

  testzulu11:
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -Dtest.java.version=11

  testopenjdk8:
    runs-on: blacksmith

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -Dtest.java.version=8

  testandroid:
    runs-on: blacksmith
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 21
          - 29
          - 34

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Configure JDK
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PandroidBuild=true :okhttp-android:test

      - name: AVD cache
        uses: useblacksmith/cache@v5
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.api-level == '34' && 'x86_64' || 'x86' }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.api-level == '34' && 'x86_64' || 'x86' }}
          script: ./gradlew -PandroidBuild=true :okhttp-android:connectedCheck :android-test:connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}

      - name: Run Release Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.api-level == '34' && 'x86_64' || 'x86' }}
          script: ./gradlew -PandroidBuild=true :android-test-app:connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}

